# Generated by Django 4.2.3 on 2023-07-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Profile',
            new_name='ContactProfile',
        ),
    ]
